services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=safeway'
      - 'MYSQL_PASSWORD=12345678'
      - 'MYSQL_ROOT_PASSWORD=12345678'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
