server:
  port: 8080


spring:
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/safeway
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: "himanshugkv11@gmail.com"
#    password: "rxscscscwavpkmlrayvcacacatej"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

#
#amazonProperties:
##  endpointUrl: https://s3.us-east-1.amazonaws.com
#  region: us-oeastp0-1
#  accessKey: AKIA3KVT3VcscscsCWHD3GHSKN
#  secretKey: 3aZt2ntXKrCUZOcscscslmX4ZXnWJQN3NuKtnMWr6LlDan
#  bucketName: 01prod-01safeway0101


# App Properties
userservice:
  app:
    jwtSecret: "======================SAFEWAY=Spring==========================="
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 86400000



