server:
  port: 8080


spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/safeway
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: creat
#              create-target: create.sql
#              create-source: metadata



  mail:
    host: smtp.gmail.com
    port: 587
    username: "himanshugkv11@gmail.com"
    password: "rxwavpkmlrayvtej"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# App Properties
userservice:
  app:
    jwtSecret: "======================SAFEWAY=Spring==========================="
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 86400000



